# Generated by Django 4.2.1 on 2023-05-09 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('game_played', models.IntegerField(default=0)),
                ('quiz_score', models.IntegerField(default=0)),
                ('quiz_taken', models.IntegerField(default=0)),
                ('day_streak', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64, unique=True)),
                ('tran_th', models.TextField()),
                ('tran_eng', models.TextField()),
                ('antonyms', models.ManyToManyField(blank=True, related_name='word_antonyms', to='api.word')),
            ],
        ),
        migrations.CreateModel(
            name='WordRoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.CharField(max_length=64, unique=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='word_root_images/')),
            ],
        ),
        migrations.CreateModel(
            name='WordLearned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('word_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.word')),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='root_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.wordroot'),
        ),
        migrations.AddField(
            model_name='word',
            name='synonyms',
            field=models.ManyToManyField(blank=True, related_name='word_synonyms', to='api.word'),
        ),
    ]
