# Generated by Django 4.2.1 on 2023-05-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='antonyms',
            field=models.ManyToManyField(blank=True, to='api.word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='synonyms',
            field=models.ManyToManyField(blank=True, to='api.word'),
        ),
    ]
