# Generated by Django 4.2.1 on 2023-06-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_user_is_playing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_playing',
            new_name='daily_play',
        ),
        migrations.AddField(
            model_name='user',
            name='is_played',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='word',
            name='part_of_speech',
            field=models.CharField(choices=[('noun', 'Noun'), ('pronoun', 'Pronoun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('preposition', 'Preposition'), ('conjunction', 'Conjunction'), ('interjection', 'Interjection')], default='noun', max_length=20),
        ),
    ]
