# Generated by Django 4.2.1 on 2023-06-01 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_rename_is_playing_user_daily_play_user_is_played_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_quiz',
            new_name='is_quized',
        ),
    ]
