# Generated by Django 4.2.1 on 2023-06-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_rename_is_quiz_user_is_quized'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quiz_percent',
            field=models.FloatField(default=0),
        ),
    ]
